### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by st1x51** [st1x51/CSPSP_ADQ#3]
- [x] Half-Life Sprite fix
- [x] Better buy menu
- [x] vfpu hlmdl
- [x] RenderFX support QC
- [x] RenderFX support Engine
- [x] wepsequence for hlmdl
